# Generated by Django 4.2.20 on 2025-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'work'), ('personal', 'pesonal'), ('urgent', 'urgent'), ('other', 'other')], default='work', max_length=20),
        ),
    ]
